# Generated by Django 5.2.14 on 2026-09-28 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e hora')),
                ('usuario_nome', models.CharField(blank=True, max_length=150, verbose_name='Usuário')),
                ('acao', models.CharField(choices=[('INCLUSAO', 'Inclusão'), ('ALTERACAO', 'Alteração'), ('EXCLUSAO', 'Exclusão')], max_length=10, verbose_name='Ação')),
                ('objeto_id', models.CharField(max_length=64, verbose_name='ID do registro')),
                ('objeto_descricao', models.CharField(max_length=255, verbose_name='Registro')),
                ('alteracoes', models.JSONField(blank=True, default=list, verbose_name='Alterações')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Tipo de registro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-data_hora', '-id'],
                'indexes': [models.Index(fields=['tipo', 'objeto_id'], name='auditoria_r_tipo_id_5d5a95_idx')],
            },
        ),
    ]
