# Generated by Django 5.2.14 on 2026-09-28 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e hora')),
                ('usuario_informado', models.CharField(max_length=150, verbose_name='Usuário informado')),
                ('motivo', models.CharField(choices=[('SENHA', 'Senha incorreta'), ('INEXISTENTE', 'Usuário não cadastrado'), ('DESATIVADO', 'Usuário desativado')], max_length=12, verbose_name='Motivo')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('navegador', models.CharField(blank=True, max_length=255, verbose_name='Navegador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa de login malsucedida',
                'verbose_name_plural': 'Tentativas de login malsucedidas',
                'ordering': ['-data_hora', '-id'],
            },
        ),
    ]
