# Generated by Django 5.2.14 on 2026-09-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0004_manutencao_email_aviso_revisao_enviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
            ],
        ),
        migrations.AddField(
            model_name='manutencao',
            name='tipo',
            field=models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva')], default='PREVENTIVA', max_length=15),
        ),
        migrations.CreateModel(
            name='PecaUsada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_total_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_usadas', to='manutencoes.manutencao')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencoes.peca')),
            ],
        ),
    ]
