# Generated by Django 5.2.14 on 2026-09-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0005_peca_manutencao_tipo_pecausada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'ordering': ['nome', 'marca'], 'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.AlterModelOptions(
            name='pecausada',
            options={'verbose_name': 'Peça usada', 'verbose_name_plural': 'Peças usadas'},
        ),
    ]
