"""
Django settings for FlowMigao project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

from .ambiente import banco_mysql_da_url, ler_bool, ler_lista

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis de ambiente do arquivo .env (credenciais do banco, e-mail etc.)
load_dotenv(BASE_DIR / '.env')

# O Railway define RAILWAY_ENVIRONMENT_ID em todos os deploys
NO_RAILWAY = bool(os.getenv('RAILWAY_ENVIRONMENT_ID'))


# Checklist de produção: https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# DEBUG fica ligado no computador local e desligado no Railway, a menos que DJANGO_DEBUG diga o contrário.
DEBUG = ler_bool('DJANGO_DEBUG', padrao=not NO_RAILWAY)

# Em produção a chave secreta é obrigatória e vem só da variável de ambiente.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('Defina a variável DJANGO_SECRET_KEY para rodar com DEBUG desligado.')
    SECRET_KEY = 'django-insecure-somente-para-desenvolvimento-local'

# Endereços pelos quais o site pode ser acessado
ALLOWED_HOSTS = ler_lista('DJANGO_ALLOWED_HOSTS') or ['localhost', '127.0.0.1', '[::1]']
CSRF_TRUSTED_ORIGINS = ler_lista('DJANGO_CSRF_TRUSTED_ORIGINS')

if NO_RAILWAY:
    # Domínio público gerado pelo Railway (ex.: flowmigao-production.up.railway.app)
    dominio_railway = os.getenv('RAILWAY_PUBLIC_DOMAIN')
    if dominio_railway:
        ALLOWED_HOSTS.append(dominio_railway)
        CSRF_TRUSTED_ORIGINS.append(f'https://{dominio_railway}')
    # O healthcheck do Railway chega com este host
    ALLOWED_HOSTS.append('healthcheck.railway.app')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clientes',
    'veiculos',    
    'manutencoes.apps.ManutencoesConfig',
    'usuarios.apps.UsuariosConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware', # Entrega Arquivos Estaticos: JavaScript 
        
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Todas as páginas exigem login, exceto as marcadas com @login_not_required (login e /saude/)
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flowmigao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flowmigao.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Ordem de prioridade:
#   1. DATABASE_URL (no Railway: DATABASE_URL=${{MySQL.MYSQL_URL}})
#   2. DB_ENGINE=sqlite
#   3. DB_NAME, DB_USER, DB_PASSWORD, DB_HOST e DB_PORT (MySQL local)

if os.getenv('DATABASE_URL'):
    conexao_mysql = banco_mysql_da_url(os.getenv('DATABASE_URL'))
elif os.getenv('DB_ENGINE', 'mysql').lower() == 'sqlite':
    conexao_mysql = None
else:
    conexao_mysql = {
        'NAME': os.getenv('DB_NAME', 'flowmigao'),
        'USER': os.getenv('DB_USER', 'flowmigao'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }

if conexao_mysql is None:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            **conexao_mysql,
            # Reaproveita a conexão por até 60s em produção e testa se ainda está viva antes de usar
            'CONN_MAX_AGE': 0 if DEBUG else 60,
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
            'TEST': {
                'CHARSET': 'utf8mb4',
                'COLLATION': 'utf8mb4_unicode_ci',
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Login: a tela de login é a primeira do sistema
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

if not DEBUG:
    # WhiteNoise serve os arquivos compactados e com nome versionado (cache longo no navegador)
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }


# Segurança em produção (HTTPS). O Railway entrega o HTTPS e avisa o Django pelo cabeçalho X-Forwarded-Proto.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    # O healthcheck do Railway acessa por HTTP interno; não pode ser redirecionado
    SECURE_REDIRECT_EXEMPT = [r'^saude/$']
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_HSTS_SECONDS', str(60 * 60 * 24 * 30)))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # A lista de "HSTS preload" dos navegadores só aceita domínio próprio; *.up.railway.app é do Railway.
    SILENCED_SYSTEM_CHECKS = ['security.W021']

    # Registra erros e avisos no console, que aparece na aba "Logs" do Railway
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {'console': {'class': 'logging.StreamHandler'}},
        'root': {'handlers': ['console'], 'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO')},
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# E-mail
# Com BREVO_API_KEY definida, envia pela API HTTPS do Brevo (necessário no Railway, que bloqueia SMTP).
# Sem ela, usa SMTP com as variáveis EMAIL_* abaixo.
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '')
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND') or (
    'flowmigao.email_brevo.BrevoEmailBackend' if BREVO_API_KEY
    else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost') # Substitua pelo host SMTP real do serviço de e-mail que você usará (ex: 'smtp.gmail.com' para Gmail)
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587')) # Substitua pela porta real do serviço de e-mail (ex: 587 para Gmail com TLS, 465 para SSL)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'email@email.com') # Substitua pelo e-mail real que enviará os avisos
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'senha#senha') # Substitua pela senha real do e-mail (ou senha de app, se usar autenticação em duas etapas)
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in (
    '1',
    'true',
    'yes',
    'sim',
)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'flowmigao@localhost')


# Aviso de revisão por e-mail
AVISO_REVISAO_EMAIL_SERVICO_ATIVO = os.getenv(
    'AVISO_REVISAO_EMAIL_SERVICO_ATIVO',
    'True',
).lower() in ('1', 'true', 'yes', 'sim')
AVISO_REVISAO_EMAIL_HORARIO_ENVIO = os.getenv(
    'AVISO_REVISAO_EMAIL_HORARIO_ENVIO',
    '08:00', # Horário diário de envio no formato HH:MM (24h)
)
AVISO_REVISAO_EMAIL_DIAS_ANTECEDENCIA = int(
    os.getenv('AVISO_REVISAO_EMAIL_DIAS_ANTECEDENCIA', '7')
)
AVISO_REVISAO_EMAIL_ASSUNTO = os.getenv(
    'AVISO_REVISAO_EMAIL_ASSUNTO',
    'Lembrete de revisão do veículo',
)
