"""
Django settings for FlowMigao project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis de ambiente do arquivo .env (credenciais do banco, e-mail etc.)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7y62ytnlvnuu1-3jl5zsmmz33qmlkm6g6at^r#bv&=td@@%643'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clientes',
    'veiculos',    
    'manutencoes.apps.ManutencoesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware', # Entrega Arquivos Estaticos: JavaScript 
        
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flowmigao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flowmigao.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv('DB_ENGINE', 'mysql').lower() == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'flowmigao'),
            'USER': os.getenv('DB_USER', 'flowmigao'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
            'TEST': {
                'CHARSET': 'utf8mb4',
                'COLLATION': 'utf8mb4_unicode_ci',
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# E-mail
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost') # Substitua pelo host SMTP real do serviço de e-mail que você usará (ex: 'smtp.gmail.com' para Gmail)
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587')) # Substitua pela porta real do serviço de e-mail (ex: 587 para Gmail com TLS, 465 para SSL)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'email@email.com') # Substitua pelo e-mail real que enviará os avisos
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'senha#senha') # Substitua pela senha real do e-mail (ou senha de app, se usar autenticação em duas etapas)
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in (
    '1',
    'true',
    'yes',
    'sim',
)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'flowmigao@localhost')


# Aviso de revisão por e-mail
AVISO_REVISAO_EMAIL_SERVICO_ATIVO = os.getenv(
    'AVISO_REVISAO_EMAIL_SERVICO_ATIVO',
    'True',
).lower() in ('1', 'true', 'yes', 'sim')
AVISO_REVISAO_EMAIL_HORARIO_ENVIO = os.getenv(
    'AVISO_REVISAO_EMAIL_HORARIO_ENVIO',
    '08:00', # Horário diário de envio no formato HH:MM (24h)
)
AVISO_REVISAO_EMAIL_DIAS_ANTECEDENCIA = int(
    os.getenv('AVISO_REVISAO_EMAIL_DIAS_ANTECEDENCIA', '7')
)
AVISO_REVISAO_EMAIL_ASSUNTO = os.getenv(
    'AVISO_REVISAO_EMAIL_ASSUNTO',
    'Lembrete de revisão do veículo',
)
